---
apiVersion: v1
kind: Service
metadata:
  name: basketapi-service
spec:
  selector:
    app: basketapi
  ports:
    - protocol: TCP
      port: 6001
      targetPort: 8080
      name: http
#    - protocol: TCP
#      port: 6061
#      targetPort: 8081
#      name: https
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: basketapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basketapi
  #  strategy:
  #    type: Recreate
  template:
    metadata:
      labels:
        app: basketapi
    spec:
      containers:
        - name: basketapi
          image: aspnetmsshop.azurecr.io/basketapi:latest
          ports:
            - containerPort: 8080
              protocol: TCP
#            - containerPort: 8081
#              protocol: TCP
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: ASPNETCORE_HTTP_PORTS
              value: "8080"
            - name: ConnectionStrings__Database
              value: "Server=basketdb-service;Port=5432;Database=BasketDb;User Id=postgres;Password=postgres;Include Error Detail=true"
            - name: ConnectionStrings__Redis
              value: "distributedcache:6379"
            - name: GrpcSettings__DiscountUrl
              value: http://discountgrpc-service:6002
            - name: MessageBroker__Host
#              value: "amqp://ecommerce-mq:5672"
              value: "amqp://guest:guest@messagebroker:5672"
            - name: MessageBroker__Username
              value: guest
            - name: MessageBroker__Password
              value: guest
          imagePullPolicy: Always
      imagePullSecrets:
        - name: acr-secret
      restartPolicy: Always
