---
apiVersion: v1
kind: Service
metadata:
  name: basketdb-service
spec:
  selector:
    app: basketdb
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: basketdb-deployment
  labels:
    app: basketdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basketdb
  template:
    metadata:
      labels:
        app: basketdb
    spec:
      containers:
        - name: basketdb
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_DB
              value: "BasketDb"
          volumeMounts:
            - name: basketdb-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: basketdb-data
          persistentVolumeClaim:
            claimName: basketdb-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: basketdb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
