---
apiVersion: v1
kind: Service
metadata:
  name: catalogapi-service
spec:
  selector:
    app: catalogapi
  ports:
    - protocol: TCP
      port: 6000
      targetPort: 8080
      name: http
#    - protocol: TCP
#      port: 6060
#      targetPort: 8081
#      name: https
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalogapi
#  strategy:
#    type: Recreate
  template:
    metadata:
      labels:
        app: catalogapi
    spec:
      containers:
        - name: catalogapi
          image: aspnetmsshop.azurecr.io/catalogapi:latest
          ports:
            - containerPort: 8080
              protocol: TCP
#            - containerPort: 8081
#              protocol: TCP
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: ASPNETCORE_HTTP_PORTS
              value: "8080"
            - name: ConnectionStrings__Database
              value: "Server=catalogdb-service;Port=5432;Database=CatalogDb;User Id=postgres;Password=postgres;Include Error Detail=true"
          imagePullPolicy: Always
      imagePullSecrets:
        - name: acr-secret
      restartPolicy: Always
