---
apiVersion: v1
kind: Service
metadata:
  name: discountgrpc-service
spec:
  selector:
    app: discountgrpc
  ports:
    - protocol: TCP
      port: 6002
      targetPort: 8080
      name: http
#    - protocol: TCP
#      port: 6062
#      targetPort: 8081
#      name: https
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: discountgrpc-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discountgrpc
  #  strategy:
  #    type: Recreate
  template:
    metadata:
      labels:
        app: discountgrpc
    spec:
      containers:
        - name: discountgrpc
          image: aspnetmsshop.azurecr.io/discountgrpc:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          #            - containerPort: 8081
          #              protocol: TCP
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: ASPNETCORE_HTTP_PORTS
              value: "8080"
            - name: ConnectionStrings__Database
              value: Data Source=discountdb
          imagePullPolicy: Always
      imagePullSecrets:
        - name: acr-secret
      restartPolicy: Always
