---
apiVersion: v1
kind: Service
metadata:
  name: eshopweb-service
spec:
  type: NodePort
  selector:
    app: eshopweb
  ports:
    - name: http
      protocol: TCP
      port: 6005
      targetPort: 8080
      nodePort: 30000
#    - protocol: TCP
#      port: 6065
#      targetPort: 8081
#      name: https
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eshopweb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eshopweb
  #  strategy:
  #    type: Recreate
  template:
    metadata:
      labels:
        app: eshopweb
    spec:
      containers:
        - name: eshopweb
          image: aspnetmsshop.azurecr.io/eshopweb:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          #            - containerPort: 8081
          #              protocol: TCP
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: ASPNETCORE_HTTP_PORTS
              value: "8080"
            - name: ApiSettings__APIGateway
              value: "http://yarpapigateway-service:6004"
          imagePullPolicy: Always
      imagePullSecrets:
        - name: acr-secret
      restartPolicy: Always
