---
apiVersion: v1
kind: Service
metadata:
  name: yarpapigateway-service
spec:
  selector:
    app: yarpapigateway
  ports:
    - protocol: TCP
      port: 6004
      targetPort: 8080
      name: http
#    - protocol: TCP
#      port: 6064
#      targetPort: 8081
#      name: https
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yarpapigateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yarpapigateway
  #  strategy:
  #    type: Recreate
  template:
    metadata:
      labels:
        app: yarpapigateway
    spec:
      containers:
        - name: yarpapigateway
          image: aspnetmsshop.azurecr.io/yarpapigateway:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          #            - containerPort: 8081
          #              protocol: TCP
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: ASPNETCORE_HTTP_PORTS
              value: "8080"
            - name: ClustersAddress__CatalogCluster
              value: "http://catalogapi-service:6000"
            - name: ClustersAddress__BasketCluster
              value: "http://basketapi-service:6001"
            - name: ClustersAddress__OrderingCluster
              value: "http://orderingapi-service:6003"
          imagePullPolicy: Always
      imagePullSecrets:
        - name: acr-secret
      restartPolicy: Always
