
services:
  catalogdb:
    image: postgres

  basketdb:
    image: postgres

  distributedcache:
    image: redis

  orderdb:
    image: mcr.microsoft.com/mssql/server

  messagebroker:
    image: rabbitmq:management

  identitydb:
    image: postgres

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.2

  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.2

  elasticsearch.setup:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.2

  catalog.api:
    image: ${DOCKER_REGISTRY?error}/catalogapi:latest
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY?error}/basketapi:latest
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

  discount.grpc:
    image: ${DOCKER_REGISTRY?error}/discountgrpc:latest
    build:
      context: .
      dockerfile: Services/Discount/Discount.Grpc/Dockerfile

  ordering.api:
    image: ${DOCKER_REGISTRY?error}/orderingapi:latest
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile

  yarpapigateway:
    image: ${DOCKER_REGISTRY?error}/yarpapigateway:latest
    build:
      context: .
      dockerfile: ApiGateways/YarpApiGateway/Dockerfile

  eshop.web:
    image: ${DOCKER_REGISTRY?error}/eshopweb:latest
    build:
      context: .
      dockerfile: WebApp/EShop.Web/Dockerfile

  identity.api:
    image: ${DOCKER_REGISTRY?error}/identityapi:latest
    build:
      context: .
      dockerfile: Services/Identity/Identity.API/Dockerfile

volumes:
  postgres_catalog:
  postgres_basket:
  postgres_identity:
  elasticsearch-data:
