
services:
  catalogdb:
    container_name: catalogdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=CatalogDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_catalog:/var/lib/postgresql/data/

  basketdb:
    container_name: basketdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=BasketDb
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - postgres_basket:/var/lib/postgresql/data/

  distributedcache:
    container_name: distributedcache
    restart: always
    ports:
      - "6379:6379"

  orderdb:
    container_name: orderdb
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=123456Abc
    restart: always
    ports:
      - "1433:1433"

  messagebroker:
    container_name: messagebroker
    hostname: ecommerce-mq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  identitydb:
    container_name: identitydb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=IdentityDb
    restart: always
    ports:
      - "5436:5432"
    volumes:
      - postgres_identity:/var/lib/postgresql/data/

  elasticsearch:
    container_name: elasticsearch
    environment:
      # - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node # Only for dev
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=elastic
      - KIBANA_PASSWORD=kibana
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    # healthcheck:
    #   test: ["CMD", "curl", "-u", "elastic:elastic", "-f", "http://elasticsearch:9200"]
    #   interval: 10s
    #   timeout: 10s
    #   retries: 5

  kibana:
    container_name: kibana
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_system # kibana_system for kibana built-in
      - ELASTICSEARCH_PASSWORD=kinaba
    depends_on:
      - elasticsearch
      - elasticsearch.setup
    ports:
      - "5601:5601" 

  elasticsearch.setup:
    container_name: elasticsearch.setup
    depends_on:
      - elasticsearch
    entrypoint: >
      sh -c "until curl -u elastic:elastic -s http://elasticsearch:9200; do echo 'Waiting for ES...'; sleep 5; done;
             echo 'Reset kibana_system password... 1';
             echo 'Reset kibana_system password... 2';
             curl -u elastic:elastic -X POST http://elasticsearch:9200/_security/user/kibana_system/_password -H 'Content-Type: application/json' -d '{\"password\": \"kinaba\"}';
             echo 'Reset kibana_system password completed';"
    restart: "no"
    # curl -u elastic:elastic -X POST http://elasticsearch:9200/_security/user/kinaba -H 'Content-Type: application/json' -d '{"password": "kinaba", "roles": ["kibana_admin"]}';

  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=aspnetapp
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ConnectionStrings__Database=Server=catalogdb;Port=5432;Database=CatalogDb;User Id=postgres;Password=postgres;Include Error Detail=true
      - ElasticConfiguration__Uri=http://elasticsearch:9200
    depends_on:
      - catalogdb
      - elasticsearch
    ports:
      - "6000:8080"
      - "6060:8081"
    volumes:
      - ~/.microsoft/usersecrets:/usersecrets:ro
      - ~/.aspnet/https:/https:ro

  basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=aspnetapp
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ConnectionStrings__Database=Server=basketdb;Port=5432;Database=BasketDb;User Id=postgres;Password=postgres;Include Error Detail=true
      - ConnectionStrings__Redis=distributedcache:6379
      - GrpcSettings__DiscountUrl=https://discount.grpc:8081
      - MessageBroker__Host=amqp://ecommerce-mq:5672
      - MessageBroker__Username=guest
      - MessageBroker__Password=guest
      - ElasticConfiguration__Uri=http://elasticsearch:9200
    depends_on:
      - basketdb
      - distributedcache
      - discount.grpc
      - messagebroker
      - elasticsearch
    ports:
      - "6001:8080"
      - "6061:8081"
    volumes:
      - ~/.microsoft/usersecrets:/usersecrets:ro
      - ~/.aspnet/https:/https:ro

  discount.grpc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=aspnetapp
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ConnectionStrings__Database=Data Source=discountdb
      - ElasticConfiguration__Uri=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    ports:
      - "6002:8080"
      - "6062:8081"
    volumes:
      - ~/.microsoft/usersecrets:/usersecrets:ro
      - ~/.aspnet/https:/https:ro

  ordering.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=aspnetapp
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ConnectionStrings__Database=Server=orderdb;Database=OrderDb;User Id=sa;Password=123456Abc;Encrypt=False;TrustServerCertificate=True
      - MessageBroker__Host=amqp://ecommerce-mq:5672
      - MessageBroker__Username=guest
      - MessageBroker__Password=guest
      - FeatureManagement__OrderFullfilment=false
      - ElasticConfiguration__Uri=http://elasticsearch:9200
    depends_on:
      - orderdb
      - messagebroker
      - elasticsearch
    ports:
      - "6003:8080"
      - "6063:8081"
    volumes:
      - ~/.microsoft/usersecrets:/usersecrets:ro
      - ~/.aspnet/https:/https:ro

  yarpapigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=aspnetapp
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ElasticConfiguration__Uri=http://elasticsearch:9200
    depends_on:
      - catalog.api
      - basket.api
      - ordering.api
      - elasticsearch
    ports:
      - "6004:8080"
      - "6064:8081"
    volumes:
      - ~/.microsoft/usersecrets:/usersecrets:ro
      - ~/.aspnet/https:/https:ro

  eshop.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=aspnetapp
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ApiSettings__APIGateway=http://yarpapigateway:8080
      - ElasticConfiguration__Uri=http://elasticsearch:9200
    depends_on:
      - yarpapigateway
      - elasticsearch
    ports:
      - "6005:8080"
      - "6065:8081"
    volumes:
      - ~/.microsoft/usersecrets:/usersecrets:ro
      - ~/.aspnet/https:/https:ro

  identity.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=aspnetapp
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ConnectionStrings__Database=Server=identitydb;Port=5432;Database=IdentityDb;User Id=postgres;Password=postgres;Include Error Detail=true
      - ElasticConfiguration__Uri=http://elasticsearch:9200
    depends_on:
      - identitydb
      - elasticsearch
    ports:
      - "6006:8080"
      - "6066:8081"
    volumes:
      - ~/.microsoft/usersecrets:/usersecrets:ro
      - ~/.aspnet/https:/https:ro
