# DEPLOY DOCKER TO AZURE CONTAINER REGISTRY
name: Deploy to Azure ACR

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy: 
    name: "Run docker build and deploy to ACR"
    runs-on: ubuntu-latest 
    environment: production

    defaults:
      run:
        shell: bash

    steps:
    # check out code
    - name: "Checkout repository"
      uses: actions/checkout@v4

    # login to azure service
    - name: "Azure login"
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.LOGIN_SERVER}}
        username: ${{ secrets.USERNAME}}
        password: ${{ secrets.PASSWORD }}

    # build docker image
    - name: "Build docker image"
      run: |
        docker build . -t ${{ secrets.LOGIN_SERVER }}/aspnetmsshop:${{ github.sha }}

    # push docker image
    - name: Azure CLI script
      uses: azure/CLI@v2
      with:
        azcliversion: latest
        inlineScript: |
          az acr login --name ${{ secrets.REGISTRY_NAME }}
          docker-compose up
          docker-compose push

    # - name: "Push docker image"
    #   run: |
    #     docker push ${{ secrets.LOGIN_SERVER }}/aspnetmsshop:${{ github.sha }}

    # verify images in acr 
    - name: Verify images in ACR
      run: |
        az acr repository list --name ${{ secrets.USERNAME }}
